# MOCK UP DATA SIMULATING A DATABASE CALL. FOR TESTING PURPOSES, THE DATA IS CODED HERE
EMPLOYEES = [
    {"id": 1, "first_name": "Bryan", "last_name": "Pineda", "department": "Engineering", "role": "Software Engineer", "email": "olivia.bennett@example.com"},
    {"id": 2, "first_name": "Stefanie", "last_name": "Lopez", "department": "Engineering", "role": "DevOps Engineer", "email": "liam.carter@example.com"},
    {"id": 3, "first_name": "Steven", "last_name": "Gutierrez", "department": "Finance", "role": "Financial Analyst", "email": "emma.mitchell@example.com"},
    {"id": 4, "first_name": "Undrik2", "last_name": "Turner", "department": "Sales", "role": "Sales Representative", "email": "noah.turner@example.com"},
    {"id": 5, "first_name": "Ava", "last_name": "Parker", "department": "HR", "role": "HR Specialist", "email": "ava.parker@example.com"},
    {"id": 6, "first_name": "Israel", "last_name": "Padilla", "department": "Engineering", "role": "Backend Engineer", "email": "ethan.collins@example.com"},
    {"id": 7, "first_name": "Sophia", "last_name": "Reed", "department": "Marketing", "role": "Marketing Manager", "email": "sophia.reed@example.com"},
    {"id": 8, "first_name": "Dexter", "last_name": "Morgan", "department": "IT", "role": "Systems Administrator", "email": "mason.morgan@example.com"},
    {"id": 9, "first_name": "Isabella", "last_name": "Morgan", "department": "Engineering", "role": "QA Engineer", "email": "isabella.brooks@example.com"},
    {"id": 10, "first_name": "Lucas", "last_name": "Hayes", "department": "Finance", "role": "Accountant", "email": "lucas.hayes@example.com"},
    {"id": 11, "first_name": "Mia", "last_name": "Foster", "department": "Sales", "role": "Account Executive", "email": "mia.foster@example.com"},
    {"id": 12, "first_name": "James", "last_name": "Ward", "department": "Engineering", "role": "Frontend Engineer", "email": "james.ward@example.com"},
    {"id": 13, "first_name": "Charlotte", "last_name": "Gray", "department": "HR", "role": "Recruiter", "email": "charlotte.gray@example.com"},
    {"id": 14, "first_name": "Benjamin", "last_name": "Price", "department": "IT", "role": "Cloud Engineer", "email": "benjamin.price@example.com"},
    {"id": 15, "first_name": "Amelia", "last_name": "Stone", "department": "Marketing", "role": "Content Strategist", "email": "amelia.stone@example.com"},
    {"id": 16, "first_name": "Henry", "last_name": "Cole", "department": "Engineering", "role": "Software Engineer", "email": "henry.cole@example.com"},
    {"id": 17, "first_name": "Harper", "last_name": "Ross", "department": "Finance", "role": "Senior Analyst", "email": "harper.ross@example.com"},
    {"id": 18, "first_name": "Alexander", "last_name": "Murphy", "department": "Sales", "role": "Sales Manager", "email": "alexander.murphy@example.com"},
    {"id": 19, "first_name": "Evelyn", "last_name": "Cooper", "department": "HR", "role": "People Partner", "email": "evelyn.cooper@example.com"},
    {"id": 20, "first_name": "Daniel", "last_name": "Richardson", "department": "IT", "role": "Network Engineer", "email": "daniel.richardson@example.com"},
    {"id": 21, "first_name": "Ella", "last_name": "Cox", "department": "Engineering", "role": "Data Engineer", "email": "ella.cox@example.com"},
    {"id": 22, "first_name": "Michael", "last_name": "Howard", "department": "Marketing", "role": "SEO Specialist", "email": "michael.howard@example.com"},
    {"id": 23, "first_name": "Scarlett", "last_name": "Watson", "department": "Finance", "role": "Controller", "email": "scarlett.watson@example.com"},
    {"id": 24, "first_name": "Sebastian", "last_name": "Brooks", "department": "Engineering", "role": "Platform Engineer", "email": "sebastian.brooks@example.com"},
    {"id": 25, "first_name": "Grace", "last_name": "Bennett", "department": "Sales", "role": "Business Development Rep", "email": "grace.bennett@example.com"},
    {"id": 26, "first_name": "Jack", "last_name": "Jenkins", "department": "IT", "role": "Security Analyst", "email": "jack.jenkins@example.com"},
    {"id": 27, "first_name": "Chloe", "last_name": "Powell", "department": "HR", "role": "HR Manager", "email": "chloe.powell@example.com"},
    {"id": 28, "first_name": "William", "last_name": "Long", "department": "Engineering", "role": "Site Reliability Engineer", "email": "william.long@example.com"},
    {"id": 29, "first_name": "Lily", "last_name": "Patterson", "department": "Marketing", "role": "Brand Manager", "email": "lily.patterson@example.com"},
    {"id": 30, "first_name": "Samuel", "last_name": "Hughes", "department": "Finance", "role": "Finance Manager", "email": "samuel.hughes@example.com"},
]
