name: Backend CI

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest


  build-and-scan:
    name: Build and Scan Docker Image
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build \
            -t devops-employee-backend:${{ github.sha }} \
            .

      - name: Scan Docker image
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: devops-employee-backend:${{ github.sha }}
          format: table
          exit-code: 1
          ignore-unfixed: true
          severity: CRITICAL,HIGH
      
      - name: Save Docker image
        run: |
          docker save \
            devops-employee-backend:${{ github.sha }} \
            -o devops-employee-backend.tar

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: devops-employee-backend-${{ github.sha }}
          path: devops-employee-backend.tar
          retention-days: 1
  

  push-to-acr:
    name: Push Docker Image to ACR
    needs: build-and-scan
    environment: dev
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download Docker image artifact
        uses: actions/download-artifact@v4
        with:
          name: devops-employee-backend-${{ github.sha }}

      - name: Load Docker image
        run: |
          docker load \
            --input devops-employee-backend.tar

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Login to ACR
        run: |
          az acr login --name ${{ vars.ACR_NAME }}

      - name: Tag Docker image
        run: |
          docker tag \
            devops-employee-backend:${{ github.sha }} \
            ${{ vars.ACR_LOGIN_SERVER }}/devops-employee-backend:${{ github.sha }}

      - name: Push Docker image
        run: |
          docker push \
            ${{ vars.ACR_LOGIN_SERVER }}/devops-employee-backend:${{ github.sha }}